services: 
        studentapp: 
            build: .
            ports:
                - "8080:8080"
        sample: 
            build: .
            ports:
                - "80:80" 
            #volumes:
                #- .:/app
            #networks:
                #- host 
        #todsapp:
            #build: ../todsapp
            #ports:
                #- "9090:9090" 
            #volumes:
                #- ../todsapp:/app
            #networks:
                #- host        