apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rc
spec:
  replicas: 5
  selector:
    #matchLabels:
    #  app: nginx
    matchExpressions:
      - {key: env , operator: NotIn , values: [ab , dk , aru , shraa]}
  template: 
    metadata:  
        labels:
          env: amit
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
            protocol: TCP