apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefullset
  labels: 
    app: my-statefullset
  spec:
  selector:
    matchLabels:
      app: my-statefullset
    replicas: 5
    templete:
      metadata:
        labels:
          apps: my-statefullset
    spec:
      containers:
        - image: mysql
          name: my-statefullset-container
          ports: 
          - containerPort: 3306
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: "12345678"